### ISSUE TITLE
Multiple target loci in a sequencing run

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#132]
A number of experimental setups (e.g. linkage PCR, single-cell PCR) have more than one target locus. 
However, the keywords `pcr_target_locus`, `forward_pcr_primer_target_location`, `reverse_pcr_primer_target_location`, which are currently expected to hold only a single locus or index. Can we refine these field as holding arrays of strings/integers?

**Comment by schristley** [comment]
Yes, OpenAPI allows for `array` to be specified for the type with `items` indicating the data type of the items within the array. Something like this:

```
forward_pcr_primer_target_location:
   type: array
   items:
      type: integer

reverse_pcr_primer_target_location:
   type: array
   items:
      type: integer
```

JSON example value looks like:

```
{
   forward_pcr_primer_target_location: [5, 20, 100],
   reverse_pcr_primer_target_location: [150, 200, 210]
}
```

Now you can also have an array of objects. For example, if values in the arrays are supposed to be paired together, then it makes more sense to have an array of objects where you can unambiguously define the paired values, instead of relying on the array index, which might get out of sync.

```
primer_target_location:
   type: array
   items:
      type: object
      properties:
         forward_pcr_primer_target_location:
            type: integer
         reverse_pcr_primer_target_location:
            type: integer
```

JSON example value looks like:

```
{
   primer_target_location: [
      {
         forward_pcr_primer_target_location: 5,
         reverse_pcr_primer_target_location: 150,
      },
      {
         forward_pcr_primer_target_location: 20,
         reverse_pcr_primer_target_location: 200,
      },
      {
         forward_pcr_primer_target_location: 100,
         reverse_pcr_primer_target_location: 210,
      },
   ]
}
```
