### ISSUE TITLE
JSON error response - success is redundant?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#229]
In the error response in the ADC API we have:

```
 error_response:
    type: object
    properties:
      success:
        type: boolean
        description: >
          A false value indicates an error occured; the message contains more detail.
      message:
        type: string
        description: Detail about the error when success=false
```
Given this is an error response, and we would never have {"success":true, "message":""} should we remove the "success" field?
