### ISSUE TITLE
ADC API facets and fields response

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#236]
In the ADC API, when the "fields" query parameter is specified, it makes sense that the response either contains a list of "Rearrangement" objects or a list of "Repertoire" objects depending on the entry point used. 

When a "facets" query parameter is specified, the response is an aggregation of data that isn't really a "Rearrangement" or "Repertoire" any longer. It looks something like this:

```
[
  {"sample.pcr_target.pcr_target_locus":[["TRB"]],"count":40},
  {"sample.pcr_target.pcr_target_locus":[["IGH"]],"count":20}
]
```
This is not a list of "Repertoire" for sure. Unfortunately, the YAML states that the response from the endpoint should always be a Repeteroire in this case. Is this how we want to leave it, or should we investigate changing this??? I am not sure that YAML is rich or powerful enough to capture this case is it?

**Comment by schristley** [comment]
duplicate of issue #241

**Comment by schristley** [comment]
Actually I guess not, we still need to decide the specifics for V1.

**Comment by bcorrie** [comment]
I agree, different keys for the different types of return data makes the most sense to me.

**Comment by schristley** [comment]
The reference implementation has been update and the API docs updated on metadata-docs branch.

**Comment by bcorrie** [comment]
@schristley I think we need to change the ADC API Spec, no? It needs a "Facet" keyword in the response I think...

**Comment by bcorrie** [comment]
I added a Facet list, but the spec definition is a bit different than what you used.

I used a three-tuple response, {"field":"sample.sample_id", "value":"TWO5B", "count":10}

Thoughts? When trying to describe the two tuple {"sample.sample_id", "TWO5B", "count":10} in YAML I struggled...

Also, I think we want a oneof for the response, in the sense that the response should be one of either "Repertoire" or "Facet" and not both. I wasn't sure how to construct that, so I haven't done it yet.

**Comment by schristley** [comment]
> I added a Facet list, but the spec definition is a bit different than what you used.

Yeah, was working on it at the same time. I just eliminated the `field` and `value` keys as they are dynamic. We could change the interface for `field` but we cannot specify `value` because it can be any data type.

**Comment by bcorrie** [comment]
@schristley I think it is unclear from the spec what the Facet response should be. The spec says it should be:
```
"Facet": [
    {"count":10},
    {"count":20}
]
```
From an API documentation perspective, I don't think that is what we want. Although we can't specify the response in YAML, I think we need to document what is expected in the YAML file, no?

Does this work for YAML?

```
  facet_list:
    type: array
    items:
      type: object
      properties:
        field:
          type: string
        value:
          type: object
        count:
          type: integer
```
This would result in:
```
"Facet": [
    {"field":"subject.subject_id", "value":{"TW05B"}, "count":10},
    {"field":"subject.subject_id", "value":{"TW05A"}, "count":20}
]
```
but in a more complex object response:
```
"Facet": [
    {"field":"sample.pcr_target.pcr_target_locus", "value":{[["TRB"]]}, "count":40},
    {"field":"sample.pcr_target.pcr_target_locus", "value":{[["IGH"]]}, "count":20},
]
```

**Comment by schristley** [comment]
> Does this work for YAML?

Yes, but unfortunately the examples you show aren't valid objects for `value`. To my knowledge, OpenAPI was not designed to allow arbitrary data types, it wants a specific data type to be specified. Otherwise, technically how do you validate it is the correct type?

**Comment by bcorrie** [comment]
According to the swagger editor, this is valid OpenAPI code:
```
  facet_list:
    type: array
    items:
      type: object
      properties:
        field:
          type: string
        value:
          type: object
        count:
          type: integer
```
Which would imply the value can be any object type and still adhere to the specification.

**Comment by schristley** [comment]
JSON `object` isn't a generic type, it is name-value pairs like a python dictionary

**Comment by schristley** [comment]
Or maybe it is a generic type, how to test?

**Comment by schristley** [comment]
According to the [json schema](http://json-schema.org/latest/json-schema-core.html)

> object: An unordered set of properties mapping a string to an instance, from the JSON "object" production

**Comment by bcorrie** [comment]
If we need key/value pairs to be valid, then how about this:

```
  facet_list:
    type: array
    items:
      type: object
      properties:
        field:
          type: object
        count:
          type: integer
```
Which would result in:
```
"Facet": [
    {"field": {"subject.subject_id": "TW05B"}, "count":10},
    {"field": {"subject.subject_id": "TW05A"}, "count":20}
]
```
but in a more complex object response this:

```
"Facet": [
    {"field": {"sample.pcr_target.pcr_target_locus": [["TRB"]]}, "count":40},
    {"field": {"sample.pcr_target.pcr_target_locus": [["IGH"]]}, "count":20}
]
```

**Comment by schristley** [comment]
Then you have a `field` object with unspecified properties, which defeats your goal because that field object can contain anything. All that has done is push those unspecified properties from the `Facet` level, down to a `field` sub-level and made the more "flat" structure into a nested structure.

The only way I can see to do what you want is to have individual value fields for each type. It's ugly but not unprecedented, had to do similar things in my past life when working on compilers...

```
  facet_list:
    type: array
    items:
      type: object
      properties:
        field:
          type: string
        value_string:
          type: string
        value_integer:
          type: integer
        value_number:
          type: number
        value_boolean:
          type: boolean
        count:
          type: integer
```

If you do want this for the ADC API then you are likely setting a precedent for how the v2 facets API will operate. Not that it's a bad idea to know what the data type is...

**Comment by bcorrie** [comment]
My main point is that spec is currently vague, with only a count field specified. I think this is confusing. I was trying to make it clear in the spec that the facet response needs to specify three things:

1. The response should contain the field that was "faceted"
2. The response should contain the value for each "facet"
3. The response should contain a count for each "facet"

I actually wasn't worried about enforcing type of the value for each facet in the response, because as you state it can take on any type depending on the field that was "faceted". So it was my intent to  leave the response {"field" : {"field_name": value_object}, "count":40} as having an undefined type for value_object . The important thing that I was trying to get the spec to communicate was that for each entry there must be a field, a value, and a count.

In this way, the spec can be used for any faceted field depending on the facet field type...

Facet on field of type String: {"field": {"study.study_id": "My Study"}, "count":40}
Facet on field of type Integer: {"field": {"sample.cell_number": 4}, "count":40}
Facet on field of type Boolean:  {"field": {"sample.single_cell": True}, "count":40}
Facet on field of type Array of strings: {"field": {"sample.pcr_target.pcr_target_locus": ["TRB"]}, "count":40},

All of these follow the spec I believe... The only problem is that the spec doesn't say that the field object should contain the key/value pair for each facet item... But at least it provides the mechanism for such a structure. We could then add the fact the key/value pair should be contained in the field object in the documentation for the field so it is clear.

If the consumer of the response needs to know the type of the field, they can look up the field name (which they have) in the spec, and see what type it is supposed to be... Presumably if they queried on it, in most cases they would already know what type it is???

**Comment by schristley** [comment]
> The only problem is that the spec doesn't say that the field object should contain the key/value pair for each facet item... But at least it provides the mechanism for such a structure. We could then add the fact the key/value pair should be contained in the field object in the documentation for the field so it is clear.

We could do the exact same thing for `Facet`, it has that mechanism as well...  a facet response is a list of objects, each containing a fieldname/value pair and a count.

> make it clear in the spec that the facet response needs to specify three things

You're initial is probably the closest to doing that:

```
  facet_list:
    type: array
    items:
      type: object
      properties:
        field:
          type: string
        value:
          type: object
        count:
          type: integer
```

but if the spec says that `value` is an `object` then it really does need to be an object.

```
"Facet": [
    {"field": "subject.subject_id", value: {value:"TW05B"}, "count":10},
    {"field": "subject.subject_id", value: {value:"TW05A"}, "count":20}
]
```

```
"Facet": [
    {"field": "sample.cell_number", value: {value:5}, "count":10},
    {"field": "sample.cell_number", value: {value:7}, "count":20}
]
```

which works if a little goofy...
