### ISSUE TITLE
PBMC for cell_subset ontology

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#242]
@bussec I think this was discussed somewhere before but I forget. I'm working on a study and filling out the metadata. They've taken PBMC from blood and sequenced, so believe that I should define the fields like this:

```
tissue:"peripheral blood"
cell_subset:
  id: "CL_2000001"
  name: "peripheral blood mononuclear cell"
```

However CL_2000001 is not under the CL_0000542 "lympocyte" node in the tree. Is that problem, am I doing it right? Or should I use "T cell" because ultimately T cells were sequenced even though we didn't do any cell sorting??
