### ISSUE TITLE
sample_processing_id in Rearrangements and Repertoire spec

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#249]
In https://github.com/airr-community/airr-standards/issues/181#issuecomment-478657199

We discussed having three _id fields at the rearrangement level to disambiguate mapping rearrangements back to different combinations of repertoires, samples, and data processing.

> 
> At the AIRR TSV level, although sequence_id is necessary, I don't think it is sufficient in that:
> 
> 1. If a specific sequence_id is processed by two different SoftwareProcessing pipelines (e.g. igblast and mixcr) then we need to be able to differentiate them in an AIRR TSV file with a SoftwareProcessingID.
> 2. If we want to be able to identify which SampleProcessing regime was applied to get to a specific SequencingRun we need the SampleProcessingID. Although it is possible to go from a sequence_id in an AIRR TSV file to specific SequencingRun entity that came from a specific sample processing regime, without the SampleProcessingID in the AIRR TSV the only way to determine that link is to search the entire set of fasta/fastq files for the sequence_id (correct me if I am wrong).
> 3. If we want to provide a mechanism to tell which Repertoire (the abstract organizational unit of analysis that is defined by the researcher) a single line in an AIRR TSV file comes from, then we need a RepertoireID.
> 
> I think if we don't have all three and given our current metadata structure we lose the ability to differentiate at one of these levels. At the same time, it appears there are arguments that both the current structure is desirable and the there is a need for identifying things from the AIRR TSV file at each of these levels.
> 
> Given the level of complexity of the metadata structure that we are capturing and the relatively small amount of added information at the rearrangement level (three identifiers, RepertoireID, SampleProcessingID, and SoftwareProcessingID), it seems like having those three fields in a rearrangement would seem to make sense to me. It certainly gives us the most flexibility and power moving forward, and the lack of any one of them seems to restrict things substantially???

This seemed to have general consensus in #181 that this was reasonable, but we currently only have repertoire_id (RepertoireID from above) and data_processing_id (SoftwareProcessingID). SampleProcessingID was not added to the spec.

Reopening to revisit...

**Comment by bcorrie** [comment]
The problem that this is trying to solve is raised here: https://github.com/airr-community/airr-standards/issues/246#issuecomment-531381149

In the above issue we have the following example:

```
repertoire:
  repertoire_id: some-id
  sample:
    - sample_id: blood pre-treatment
    - sample_id: blood post-treatment
    - sample_id: tissue post-treatment
      disease_state_sample: cancer
  data_processing:
    - data_processing_id: 1
      primary_annotation: true
```
Consider the case where you have the above Repertoire file that describes some data of interest and an AIRR TSV with the accompanying data. You search the AIRR TSV file, and find a junction_aa of interest that you want to know more about. You get this information for the rearrangement that you found in the AIRR TSV:
```
sequence_id, repertoire_id, data_processing_id, v_call, d_call, j_call, junction_aa, ...
```
You can then look up the repertoire_id in the Repertoire file, to find out which repertoire this rearrangement came from. Lets assume repertoire_id == some_id and data_processing_id == 1 as in the above repertoire.

In this case, you have no way of telling if the rearrangement you found is from the "blood pre-treatment", "blood post-treatment", or "tissue post-treatment" sample.

Is this not a problem?

**Comment by scharch** [comment]
I'd argue that it's not a problem, but a decision by the person who merged those samples into a single repertoire that was no need to maintain the distinctions between them. Does that make the data less than infinitely reusable? Perhaps, but the whole point of the MiAIRR is that the _raw data_ is well annotated and you can always go back to that if you need to. And you could never completely avoid that necessity, anyway. And I still feel, as I said in #181, that making the `rearrangement` schema more complicated is a bad idea.

**Comment by bcorrie** [comment]
I have added a "sample_processing_id" field to the rearrangement in branch issue-249 and added the the same sample_processing_id to the Repertoire object. The sample_processing_id should be unique within the Repertoire, similar to the way data_processing_id is unique. This should be sufficient to solve this problem from a disambiguation perspective and is a relatively minor change.

The repertoire record is now:
```
repertoire:
  repertoire_id: some-id
  sample:
    - sample_processing_id: 1, sample_id: blood pre-treatment
    - sample_processing_id: 2, sample_id: blood post-treatment
    - sample_processing_id: 3, sample_id: tissue post-treatment
      disease_state_sample: cancer
  data_processing:
    - data_processing_id: 1
      primary_annotation: true
```
The rearrangement record is now:
```
sequence_id, repertoire_id, sample_processing_id, data_processing_id, v_call, d_call, j_call, junction_aa, ...
```
One can then find the specific sample within the repertoire that the rearrangement came from. Also note that this makes the treatment of data_processing and sample processing symmetric.

Going in the other direction, when performing a search for all of the rearrangements from a specific sample, it is a bit more complicated. With this _id structure, one needs to search at the rearrangement level for a repertoire_id, data_processing_id, and a sample_processing_id to ensure that you get just the rearrangements from a single sample processing and a single data processing regime.
