### ISSUE TITLE
New data_processing_files field in DataProcessing

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#276]
The DataProcessing object captures the processing that has been performed on some sequencing data. From a file perspective, we track the files from the output of a sequencing run. From a data provenance perspective, it seems helpful to provide a field to track the files produced by a DataProcessing step. We certainly track this, and from a data provenance perspective (for a data curator) it is very helpful to be able to link a file to a set of rearrangement data. 

I would suggest something like 

```
        data_processing_file:
            type: string
            description: File name for data produced by a data processing step.
            example: MS10R-NMonson-C7JR9_S1_R1_001.igblast.airr.tsv
            x-airr:
                miairr: false
                required: false
                nullable: true
                set: 5
                subset: process (computational)
                name: Processed data file name
```
This is related to #275 where I am suggesting that it would be useful to have something like:

"data_processing_file":"TW05B_T_naive_CD8.igblast.airr.tsv"

as part of the data_processing record for the Florian data.
