### ISSUE TITLE
locus_species type definition

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#278]
There's a new (ish?) field in the Rearrangement spec called `locus_species` that didn't have a `type` property, which caused the docs build to fail on RTD.

I added `type:string` in the spec on master, just to get the docs to build (see 0c02017).

Is this correct?

**Comment by javh** [comment]
From @schristley:

> @javh actually no, the field is an ontology object, $ref: '#/Ontology', so it is an object. Because $ref is specified, there should not be a type. So the doc script needs to be updated to handle that. I guess this is the first ontology field that's been added to Rearrangement.

**Comment by javh** [comment]
Okay, @schristley. I'll fix it. What should the type value be in the TSV then?

**Comment by javh** [comment]
Oh... And did we test that not having a `type` property for schema field doesn't break the R and python reference APIs?

**Comment by schristley** [comment]
The travis checks passes so I assumed everything was okay, but yeah there might be an issue somewhere. I already did a bunch of changes for the repertoire metadata, but there could be a rearrangement specific pathway...

**Comment by javh** [comment]
Just skimming over the code, I kind of expect the python API to work: `schema.Schema.type` returns None if `type` is not found) okay. But, the R API looks like it'll choke: `load_schema` expects "description" and "type" to exist.

**Comment by schristley** [comment]
It's a pull request #260, and it looks like we can revert it. Maybe we should do that until we work out handling ontology in rearrangements in more detail?

**Comment by javh** [comment]
Can we just put in a dummy type for now instead? Will that break anything? Maybe "object"?

Looks like we'll still have to tweak the R package to deal with unrecognized types, but it should probably do that anyway.

**Comment by schristley** [comment]
> Can we just put in a dummy type for now instead? Will that break anything?

Maybe, I haven't tested in the ADC API yet. It uses swagger middleware and will usually complain if something doesn't match the OpenAPI spec.

**Comment by bcorrie** [comment]
> Can we just put in a dummy type for now instead? Will that break anything? Maybe "object"?

If we use a dummy type for an ontology term, in particular in a TSV file, I would recommend using string. In particular because you can have a JSON object as a string in a TSV (e.g. {"locus_species" : {"id":10,"value":"Homo Sapiens"}} - with appropriately escaped quotes of course).

**Comment by schristley** [comment]
@javh @bussec Sorry I missed this in my review, I was assuming these fields were in repertoire metadata...

Actually this is more problematic. We haven't really talked about how to handle ontology-based fields for `Rearrangements`. The ontology definition that we use for the repertoire metadata does not conform to using the AIRR TSV format.

I think we really need to revert this PR until we discuss and decide. Hacking the python and R libraries shouldn't be done until we decide how to do this. I don't think we want `object`s in the Rearrangement schema, we have stricter requirements because of the TSV format.

**Comment by javh** [comment]
I'm cool with encoding it as a JSON string for now, as per @bcorrie's comment, until we can hammer out the details.  That's the same basic idea as we're discussing with the lineage trees (encoding a tree structure as a Newick string).

**Comment by javh** [comment]
That is unless you want to do a release before we can discuss a proper implementation... then, yeah, a revert seems like the easiest route.

**Comment by schristley** [comment]
Yeah, a release should be imminent, we want that before the ADC API paper goes to reviewers. We just need to clear out the last few ADC API issues.

**Comment by schristley** [comment]
> encoding it as a JSON string

Not really a fan. That requires packing/unpacking the JSON when you want to read/write values. You won't be able to do simple queries or searches on the fields. I think we can come up with something better.

**Comment by bcorrie** [comment]
Sounds good, was a first pass suggestion - was what jumped to mind... @schristley can you tell that I am on an airplane and have nothing better to do that catch up on email, JIRA, and GitHub issues 8-)

**Comment by schristley** [comment]
I've reverted `locus_species` from the rearrangement schema until we come up with a formal policy to use ontologies for rearrangement fields.

**Comment by bussec** [comment]
Sorry for creating such a hazzle, I'm ok with with prioritizing API stability. @schristley what could be a potential solutions for this?

**Comment by schristley** [comment]
This isn't a general solution for any object but would be specifically for ontology-based fields in the rearrangement schema. As our ontology object is an `id` and a `value`, I would propose that we split out that object into two fields. So for locus_species, there would be fields `locus_species_id` and `locus_species_value`, essentially we use a naming convention.

The challenge is that we still need something in the schema that describes the ontology (it's url and etc.). I suppose we could attach that info to both `locus_species_id` and `locus_species_value`, or we could keep `locus_species` with that info

```
        locus_species:
             $ref: '#/Ontology'
             description: blah blah
             example:
                 id: 9096
                 value: Homo sapiens
             x-airr:
                 miairr: false
                 required: false
                 nullable: true
                 format: ontology
                 ontology:
                     draft: false
                     name: NCBITAXON
                     url: https://www.ncbi.nlm.nih.gov/taxonomy
                     top_node:
                         id: 7776
                         value: Gnathostomata
        locus_species_id:
             type: string
        locus_species_value:
             type: string
```

alternatively


```
        locus_species_id:
             type: string
             description: blah blah
             example:
                 id: 9096
             x-airr:
                 miairr: false
                 required: false
                 nullable: true
                 format: ontology
                 ontology:
                     draft: false
                     name: NCBITAXON
                     url: https://www.ncbi.nlm.nih.gov/taxonomy
                     top_node:
                         id: 7776
                         value: Gnathostomata
        locus_species_value:
             type: string
             description: blah blah
             example:
                 value: Homo sapiens
             x-airr:
                 miairr: false
                 required: false
                 nullable: true
                 format: ontology
                 ontology:
                     draft: false
                     name: NCBITAXON
                     url: https://www.ncbi.nlm.nih.gov/taxonomy
                     top_node:
                         id: 7776
                         value: Gnathostomata
```
