### ISSUE TITLE
Correct root node for study_type ontology???

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#284]
Mostly for @bussec to review...

The current root node for the study_type ontology is:

```
                ontology:
                    draft: true
                    name: NCIT
                    url: https://ncit.nci.nih.gov/ncitbrowser/
                    top_node:
                        id: C15320
                        value: Study Design
```
The example in the spec is 
```
            example:
                id: C15197
                value: Case-Control Study
```
This "Case-Control Study" node is not a child of the "Study Design" root node. There is a root node called "Study" under which this lies. "Study" and "Study Design" are siblings in the tree... 

I think we might want "Study" to be the root node???

```
                ontology:
                    draft: true
                    name: NCIT
                    url: https://ncit.nci.nih.gov/ncitbrowser/
                    top_node:
                        id: C63536
                        value: Study
```
