### ISSUE TITLE
Revisit MiAIRR non-nullable fields

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#310]
Creating this issue to replace the specific issue around cell_storage in #307 (which I will close).

In the current spec the following are required and non-nullable. Note ```sample_type```, ```tissue```, and ```single_cell```  are missing from the original list in #96

Are these still the "correct" fields to be required and non-nullable?

```
        synthetic:
            type: boolean
            description: TRUE for libraries in which the diversity has been synthetically generated (e.g. phage display)
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        organism:
            $ref: '#/Ontology'
            description: Binomial designation of subject's species
            example:
                id: 9096
                value: Homo sapiens
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        cell_storage:
            type: boolean
            description: TRUE if cells were cryo-preserved between isolation and further processing
            example: TRUE
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        template_class:
            type: string
            enum:
                - DNA
                - RNA
            description: The class of nucleic acid that was used as primary starting material for the following procedures
            example: RNA
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        library_generation_method:
            type: string
            enum:
                - "PCR"
                - "RT(RHP)+PCR"
                - "RT(oligo-dT)+PCR"
                - "RT(oligo-dT)+TS+PCR"
                - "RT(oligo-dT)+TS(UMI)+PCR"
                - "RT(specific)+PCR"
                - "RT(specific)+TS+PCR"
                - "RT(specific)+TS(UMI)+PCR"
                - "RT(specific+UMI)+PCR"
                - "RT(specific+UMI)+TS+PCR"
                - "RT(specific)+TS"
                - "other"
            description: Generic type of library generation
            example: RT(oligo-dT)+TS(UMI)+PCR
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        complete_sequences:
            type: string
            enum:
                - partial
                - complete
                - "complete+untemplated"
            description: >
                To be considered `complete`, the procedure used for library construction MUST generate sequences that
                1) include the first V segment codon that encodes the mature polypeptide chain (i.e. after the
                leader sequence) and 2) include the last complete codon of the J segment (i.e. 1 bp 5' of the J->C
                splice site) and 3) provide sequence information for all positions between 1) and 2). To be considered
                `complete & untemplated`, the sections of the sequences defined in points 1) to 3) of the previous
                sentence MUST be untemplated, i.e. MUST NOT overlap with the primers used in library preparation.
            example: partial
            x-airr:
                miairr: true
                required: true
                nullable: false
```
```
        physical_linkage:
            type: string
            enum:
                - none
                - "hetero_head-head"
            description: >
                Describes the mode of linkage if a method was used which physically links nucleic acids derived from
                distinct loci in a single-cell context.
            example: hetero_head-head
            x-airr:
                miairr: true
                required: true
                nullable: false
```
