### ISSUE TITLE
Cell object specifications - ScXT

### ISSUE THREAD

**Issue by sharikrish** [airr-community/airr-standards#320]
Followed by a discussion with @franasa , @bussec; we have come up with the below schema for cell object.

```
Cell:
    discriminator: AIRR
    type: object
    required:
        - cell_id 
        - rearrangements  
        - virtual
    properties:
        cell_id:
            type: string
            description: >
                Identifier defining the cell of origin for the query sequence.
            example: W06_046_091
            x-airr:
                miairr: false
                required: true
                nullable: false
                adc-api-optional: false
                name: Cell index
        rearrangements:
            type: array
            description: >
                  List of rearrangement identifiers defined for the Rearrangement object
            items:
                type: string
            example: [id1, id2] 
            x-airr:
                miairr: false
                required: true
                nullable: true
                adc-api-optional: false
                name: 
        virtual:
            type: boolean
            description: >
                boolean to indicate if pairing was inferred.
            x-airr:
                miairr: false
                required: true
                nullable: false
                adc-api-optional: true
```

From an API perspective we have implemented cell endpoint which provides all cell associated properties such as `rearrangements`, `virtual` flag etc as per the discussion in #273 

HTTP method | URL | ACTION
-- | -- | --
GET, POST | http://[hostname]/api/cells | Retrieve list of cells
GET, POST | http://[hostname]/api/cell/[cell_id] | Retrieve a cell

For instance, the cell endpoint would return a json upon a query and it is represented as below

`curl -i -H 'Content-Type: application/json' -X POST 'http://127.0.0.1:5000/api/cells?cell_id=1086`

```
{
  "Cells": [
    {
      "cell_id": "1086", 
      "rearrangements": ["507","678"], 
      "virtual": false
    }
  ]
}
```
Some of the questions that we would like to address are as follows:

1. In the `Cell` object specifications `miairr` is set to be `false` which is different from the `cell_id` properties defined in the rearrangement object. In addition, it is obvious for single cell experiments to have `cell_id` associated with them and hence it cannot have a null value. Hence, it might be logical to have extension properties for `cell_id` similar to those discussed for race or ethnicity etc. in Human population genetics extension #318 to trigger the properties defined in the extension if study has a `cell_id`. The question would be how to centralize `cell_id` properties with the original yaml file?

2. `rearrangements` defined in `Cell` object would contain a list of `rearrangement_id` associated with the `cell_id`. From a single cell context, a cell can either have a single or sometimes none and multiple rearrangements. For instance, when one queries for a `cell_id`, all the rearrangements associated with `cell_id` needs to be retrieved and one of the best ways to define rearrangements would be as a list containing all `rearrangement_id` as defined for clone object #294 [[Line:2359]](https://github.com/airr-community/airr-standards/blob/777b6c3c5cc55f00acd1f9da0b33e2012ca9a034/specs/airr-schema.yaml#L2359)

**Comment by scharch** [comment]
> Hence, it might be logical to have extension properties for cell_id similar to those discussed for race or ethnicity etc.

@srlak These should be properties of the sample, not of the cell. Similarly, `rearrangement_id` alone isn't enough to recover the sequences. To solve both, `Cell` should include required, non-nullable fields for `repertoire_id` and `sample_id`.

**Comment by bussec** [comment]
>>    Hence, it might be logical to have extension properties for cell_id similar to those discussed for race or ethnicity etc.

> @srlak These should be properties of the sample, not of the cell. 

@scharch (assuming that this comment referred to `race` and `ethnicity`): They are actually at the `Subject` level, but IMO were just there as an example for the HPG-XT (#318) and the (currently unresolved) way how to determine whether an XT is active or not.

> Similarly, rearrangement_id alone isn't enough to recover the sequences. To solve both, Cell should include required, non-nullable fields for repertoire_id and sample_id.

Because `rearrangement_id` is not a globally unique identifier? No objections against adding the other fields, which then would be:
* `sample_id`: 1-to-1 reference, as an individual cell can only come from a single tube
* `repertoire_id`: 1-to-n reference, as our repertoire definition allows overlapping repertoires (e.g. `IgG class-switched B cells` and `CD27+ B cells`).

Correct?

**Comment by scharch** [comment]
@bussec Correct.

**Comment by bcorrie** [comment]
@bussec @srlak in the original single cell extension proposal here:

https://github.com/airr-community/airr-standards/blob/single_cell_ext/docs/miairr/miairr_single_cell_extension.rst

There were fields around DOIs, keywords, and expression value/expression marker data...

Should we have place holders for this in this spec?

**Comment by bcorrie** [comment]
One question as to the ```rearrangements``` array in the ```Cell``` object. If each rearrangement has a ```cell_id``` field, and this presumably matches the cell_id in the ```Cell``` object, do we need to have a list of ```rearrangements``` at the ```Cell``` level? Now each ```Cell``` presumably would only ever be linked with a small number of ```rearrangements``` so maybe this is not the end of the world from a data size perspective, but linking both ways can lead to data consistency issues...

**Comment by franasa** [comment]
What if the  `Rearrangement` object instead of having a duplicate of the `cell_id` inherits the whole defined `Cell` object?, this would be then also triggered only when the single cell extension is required. Does this make sense and could solve the potential consistency issues?. It's true that for small lists of `rearrangement_id`s it might not make a big difference but as far I understand from @srlak's advances on the API (correct me if I am wrong)  it gets more tricky when we start defining with how to include other single-cell specifics such as flow cytometry markers

**Comment by schristley** [comment]
> sample_id: 1-to-1 reference, as an individual cell can only come from a single tube

`sample_id` or `sample_processing_id`? `sample_id` refers to just the MiAIRR sample object excluding cell processing down to sequencing, while `sample_processing_id` refers to the set of objects from sample down to sequencing.

**Comment by schristley** [comment]
> If each rearrangement has a cell_id field, and this presumably matches the cell_id in the Cell object, do we need to have a list of rearrangements at the Cell level?

@bussec I guess we need to deprecate `cell_id` in rearrangements?

@srlak Should there be a `receptors` array with the list of receptors in the cell?

**Comment by javh** [comment]
The Cell object isn't compatible with storing Rearrangement records in a TSV, so you would still need the `cell_id` in Rearrangement for both the flat/simple representation of single-cell and as a way to link from Rearrangement to Cell records (outside of a json/yaml/database representation of Rearrangement records).

**Comment by schristley** [comment]
> the cell_id in Rearrangement for both the flat/simple representation of single-cell and as a way to link from Rearrangement to Cell records.

I was thinking we wanted to deprecate `cell_id` in rearrangements because it allows that rearrangement to only be associated with one cell. Based upon @bussec [comment](https://github.com/airr-community/airr-standards/issues/273#issuecomment-568649516), it seems like we need to support a n-to-n relationship.

**Comment by javh** [comment]
> I was thinking we wanted to deprecate `cell_id` in rearrangements because it allows that rearrangement to only be associated with one cell. Based upon @bussec [comment](https://github.com/airr-community/airr-standards/issues/273#issuecomment-568649516), it seems like we need to support a n-to-n relationship.

I don't think we want to do that. That would mean dropping single-cell support from the TSV. We need to support an n-to-n relationship, but not required it, because it's not the most common use case. 

I'm viewing Cell like Alignment - a solution for when a single reference alignment result (which is what Rearrangement supports) isn't sufficient.

**Comment by srlak** [comment]
>     * `repertoire_id`: 1-to-n reference, as our repertoire definition allows overlapping repertoires (e.g. `IgG class-switched B cells` and `CD27+ B cells`).

@bussec @scharch Would this then mean that `cell_id` is associated with multiple `repertoire_id` which then points to the associated meta-data for each `repertoire_id`?

> There were fields around DOIs, keywords, and expression value/expression marker data...
> 
> Should we have place holders for this in this spec?



@bcorrie : yes you are right and we will include it but before we need to sort out `cell_id` mapping and linkage (explained below). Excluding that we have updated the spec as below. 
In addition to this, consider a case where we have two repertoires from a single sample that has different types of Bcells (eg. IgG+Bcell and CD27+) and this would have same rearrangements that are just duplicated with different `rearrangement_id`  and would then be linked to `cell_id` with their expression data etc. and the question is how do we link all of them to `Cell` Object? Referring to #181 . and we have updated the spec below. 

```
Cell:
    discriminator: AIRR
    type: object
    required:
        - cell_id #redefined cell_id > how to centralize it in the yaml 
        - rearrangements  
        - virtual
    properties:
        cell_id:
            type: string
            description: >
                Identifier defining the cell of origin for the query sequence.
            example: W06_046_091
            x-airr:
                miairr: false
                required: true
                nullable: false
                adc-api-optional: false
                name: Cell index
        rearrangements:
            type: array
            description: >
                  Array of rearrangement identifiers defined for the Rearrangement object
            items:
                type: string
            example: [id1, id2] #empty vs NULL? 
            x-airr:
                miairr: false
                required: true
                nullable: true
                adc-api-optional: false
       raw_data:
           type:object
           description:
           properties:
                study_method: 
                    type: string
                    enum: 
                       flow cytometry
                       single-cell transcriptome
                    description: >
                       keyword describing the methodology used to assess expression. This values for this field MUST come from a controlled vocabulary
                doi:
                    type: string
                    description: >
                      DOI of raw data set containing the current event
                index:
                    type: string
                    description: >
                      Index addressing the current event within the raw data set.
        expression:
            type: object
            description: > 
                Expression definitions for single-cell
            properties:
                expression_maker: 
                    type: string
                    description: >
                       standardized designation of the transcript or epitope
                    example: CD27
                expression_value:
                    type: integer
                    description: >
                       transformed and normalized expression level.
                    example: 14567
         virtual:
            type: boolean
            description: >
                boolean to indicate if pairing was inferred.
            x-airr:
                miairr: false
                required: true
                nullable: false # assuming only done for sc experiments, otherwise does not exist
                adc-api-optional: true

```


> If each rearrangement has a `cell_id` field, and this presumably matches the cell_id in the `Cell` object, do we need to have a list of `rearrangements` at the `Cell` level?

@bcorrie : Yes. This makes sense. A naive question is `cell_id` is not a required field in `Rearrangement` object and shouldn't this be required field if it is referring to a single-cell study?
