### ISSUE TITLE
a simple proposal for repertoire groups and time course

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#374]
Comparative analysis between repertoire groups (e.g. Treatment vs. Control) is a common procedure, and time course is also an increasingly common experimental design, so it would be nice to have a simple way to define and document them in the metadata.

I have two proposals, both relatively simple. The first proposal is to have an explicit `RepertoireGroup` object that defines the group.

```
RepertoireGroup:
    discriminator: AIRR
    type: object
    properties:
        group_id:
            type: string
        group_name:
            type: string
        group_description:
            type: string
        repertoires:
            type: array
            items:
                type: string
        time_course:
            type: array
            items:
                type: string
```

I'm not sure if we need `group_id` or whether `group_name` is sufficient; it might depend a bit on how we want to manage provenance.

The `repertoires` array is a list of `repertoire_ids` (or PIDs), thus defining the group.

For time course, as `repertoires` is an array, it defines an explicit ordering of those repertoires. Then the `time_course` array, which should be the same length as `repertoires`, provides user-defined labels (e.g. ["5w", "6m", "1y"] or ["1", "2", "3"] or ["pre", "post"]) for each time point.

In terms of the file format, the metadata file has an `Info` object and a `Repertoire` array, we could just add a `RepertoireGroup` array and store it in the same file.

The other proposal is an implicit definition. Here we add a couple of fields to the `Repertoire` object.

```
Repertoire:
    discriminator: AIRR
    type: object
    properties:
        groups:
            type: array
            items:
                type: string
        time_course:
            type: string
```

This acts as a simple tagging scheme, you add user-defined "tags" to the `groups` array (e.g. ["treatment", "another"]).

Then to operate on a group, you would iterate over all of your repertoires and collect the ones with the same tag like "treatment".

For time course, I'm assuming the repertoire has just one time course label. I suppose `time_course` could also be an array, and then `groups` have to be kept in sync (order wise) with `time_course`.

This implicit definition requires that you know the set of repertoires, and there is the chance for tag conflict/confusion if repertoires from different studies are used together. There is also the question of provenance if a new study groups repertoires in a different way, i.e. adds new tags to `groups`, how would one record that? Therefore, because of these issues, I'm less inclined towards this implicit definition but I offer it as it seems even simpler.

VDJServer currently support repertoire groups, but it goes a step further by allowing the groups to be dynamically defined. For example, you can provide a "group by" variable such as `subject.subject_id` and it will create groups for each value in the variable, in this case repertoires grouped by each subject. Another method is a simple logical statement, `subject.sex == male`, to group repertoires where the statement true. By the time of execution, these all essentially get translated into a static list of repertoires like in `RepertoireGroup` above. However, we could consider something like this if we want to go beyond the simple proposal.
