### ISSUE TITLE
Revisit `physical quantity`

### ISSUE THREAD

**Issue by franasa** [airr-community/airr-standards#498]
In the Schema, the `format` attribute is defined as:
```yaml
Attributes:
        format:
            type: string
            description: Field format. If null then assume the full range of the field data type
            enum:
                - ontology
                - controlled vocabulary
                - physical quantity
```
But `physical quantity` is only used in the whole schema as a property in `disease_length` (where it should be an ontology, see #500). besides that, there is only another use of the term as part of the ontology label of `template_amount_unit` : 
```yaml
template_amount_unit:
...
                ontology:
                    draft: false
                    top_node:
                        id: UO:0000002
                        label:  physical quantity 
```
Where the actual label of `UO:0000002`  in the UO ontology is `mass unit`.

a) Is `physical quantity` a format itself or should it be considered  as part of the UO `ontology` ?
b) and should the label of the `template_amount_unit`ontology be `mass unit`?
