### ISSUE TITLE
Use CURIEs to link Germline to Repertoire/Rearrangement

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#553]
Should resolve Task 3 in #157 

- link repertoire/rearrangement to germline. The link is currently at the rearrangement level but might want to reconsider this, maybe at the repertoire level with software processing and annotation.

See https://github.com/airr-community/airr-standards/issues/157#issuecomment-921872075 for discussion.

**Comment by schristley** [comment]
That task item is old, it's saying the germline database link is at the rearrangement level, but this is no longer true, it was put in DataProcessing awhile ago. Unless this is referring to something else...

**Comment by bcorrie** [comment]
For me this is addressing something else. The issue that this is capturing is formalizing that we will use CURIEs to refer to Germline objects, either Germline sets or Germline Genes - currently we have no formal indication as to what format fields like germline_set_id and germline_database take on and the formats we do have aren't really "computable". A generic string designation is "unsatisfactory" and CURIEs solve this problem 8-)

From https://github.com/airr-community/airr-standards/issues/157#issuecomment-921872075 (with some edits) I suggested we could use CURIE nomenclature for Germline IDs as follows:

- In our current DataProcessing object, we have germline_database. This could either be changed to refer to a CURIE that points to a GermlineSet (e.g. germline_database = "OGRDB_GERMLINESET:42") rather than a string or to treat it like an ontology if we want to have a text description of the germline database used as well as have an identifier for it (e.g. germline_database.label = "OGRDB Germline, downloaded 2021-09-17" and germline_database.id = "OGRDB_GERMLINESET:42". Similarly, this could be used to provide a more concise description when an IMGT germline set is used (e.g. germline_database = "IMGT:201736-4"). Presumably even if we re-engineer DataProcessing, something similar would still exist. DataProcessing objects will need to refer to the GermlineSets that were used to perform the data processing...
- subject.genotype already refers to GermlineSets, so no work needs to be done there to reference GermlineSet but we need to specify a more rigorous mechanism for specifying a germline_set_id.
- If we wanted to go even further, we could add rearrangement fields that store gene IDs for VDJC calls. v_call = "IGHV1-1*01", v_call_id = "OGRDB_GENE:44". This of course could be derived from going back to the Repertoire and presumably looking up v_call in the germline_database stored in the DataProcessing object so would be redundant.

**Comment by bcorrie** [comment]
@williamdlees a question regarding connecting OGRDB Germline Sets to the AIRR Schema. I was just looking at OGRDB's germline sets, and was wondering if I understood how things were working.

On OGRDB the ID of the Germline Set is referenced in the URL as such: https://ogrdb.airr-community.org/germline_set/3

On the History tab for this germline set it says this is G00003.

If I wanted to refer to this Germline Set in the AIRR Schema how would I go about doing that? There seem to be two places where this might occur:

`Genotype.documented_alleles.germline_set_ref`
`GermlineSet.germline_set_id`

If we used the AIRR CURIE schema, we could have an OGRDB CURIEMap as follows:

```
  OGRDB_GERMLINESET:
    type: catalog
    default:
      map: OGRDB
      provider: OGRDB
    map:
      OGRDB:
        iri_prefix: "https://ogrdb.airr-community.org/germline_set/"
```

If I then set `Genotype.documented_alleles.germline_set_ref = "OGRDB_GERMLINESET:3"` then that CURIE would resolve to:

https://ogrdb.airr-community.org/germline_set/3

Now this is different than what you have in the AIRR Spec description, as the description for `Genotype.documented_alleles.germline_set_ref` says:

```
        germline_set_ref:
            type: string
            description: Unique identifier of the germline set and version, in standardized form (Repo:Label:Version)
            example: OGRDB:Human_IGH:2021.11
            x-airr:
                nullable: false
```
What are your thoughts on using the CURIE mechanism above to resolve this field? If you look at the versions tab on OGRDB for this Germline it has all the above information:
```
[BALB/c IGH](https://ogrdb.airr-community.org/germline_set/3)	Mouse	BALB/c	IGH	1	2022-02-28
```
