### ISSUE TITLE
collection_time_point_relative has string example instead of number

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#659]
```
        collection_time_point_relative:
            type: number
            nullable: true
            description: Time point at which sample was taken, relative to `Collection time event`
            title: Sample collection time
            example: "14"
            x-airr:
                miairr: important
                adc-query-support: true
                set: 2
                subset: sample
                name: Sample collection time
```

should have `example: 14`
