### ISSUE TITLE
Minor germline style issues

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#673]
```
Genotype:
        inference_process:
            type: string
            enum:
                - "genomic_sequencing"
                - "repertoire_sequencing"
```
Should `repertoire_sequencing` be split into mRNA and gDNA sequencing?

```
AllelleDescription:
        inference_type:
            type: string
            enum:
                - "Genomic and rearranged"
                - "Genomic only"
                - "Rearranged only"
```

Use of spaces and capitals is inconsistent with other germline fields. Should these be `snake_case`?
