### ISSUE TITLE
Annotation of absence of specific MHC alleles

### ISSUE THREAD

**Issue by ndalchau** [airr-community/airr-standards#678]
How should one represent information about a subject not expressing a particular MHC allele? In the study published [here](https://jitc.bmj.com/content/8/2/e001631.long#DC1), there is information about which subjects express HLA-A*02:01 (A2) and which do not.

For the A2-positive subjects, you can specify a single entry in `mhc_alleles`, like this:
```yaml
subject:
  genotype:
    mhc_genotype_set:
      mhc_genotype_list: [ 
        mhc_class: "MHC-I"
        mhc_alleles: [
          { allele_designation: "02:01", gene: { id: "MRO:0000046", label: "HLA-A"} }
        ]
      ]            
```

But what is recommended for A2-negative subjects? Leaving `mhc_alleles` or `mhc_genotype_list` empty is not satisfying, because that doesn't communicate the fact that they do not express A2. 

Maybe an extended schema could incorporate an additional `genotype`, such as `non_expressed_mhc_genotypes`, but I can imagine there would be reluctance to extend the schema for this purpose.
